apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot-dev
  template:
    metadata:
      labels:
        app: polybot-dev
    spec:
      containers:
      - name: polybot-dev
        image: 352708296901.dkr.ecr.us-west-1.amazonaws.com/jihad-polybot-dev:0.0.31
        ports:
        - containerPort: 8443
        env:
          - name: TELEGRAM_TOKEN
            value: "7024108948:AAHB_gwmjGqrayt3kE2yDO0lg_fJTbkXuTE"
          - name: TELEGRAM_APP_URL
            value: "https://polybotjihaddev.devops-int-college.com/"
          - name: S3_BUCKET_NAME
            value: "jihadar-dev"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
             secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
          - name: TELEGRAM_TOKEN
            valueFrom:
             secretKeyRef:
              name: telegram-secret
              key: token
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
             secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 10
          periodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service-dev
  namespace: dev
spec:
  selector:
    app: polybot-dev
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443