apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-deployment-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5-dev
  template:
    metadata:
      labels:
        app: yolo5-dev
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-5-190.us-west-1.compute.internal
      containers:
      - name: yolo5-dev
        image: IMG_URL
        ports:
        - containerPort: 8080
        env:
          - name: BUCKET_NAME
            value: "jihadar-dev"
          - name: SQS_QUEUE_NAME
            value: "jihad-dev"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            cpu: "100m"
            memory: "150Mi"
          limits:
            cpu: "500m"
            memory: "3Gi"